import Head from "next/head";
import Image from "next/image";

import { GiMountains } from "react-icons/gi";
import { HiMagnifyingGlass } from "react-icons/hi2";
import { IoIosMan } from "react-icons/io";
import { BiWorld } from "react-icons/bi";
import { VscPlayCircle } from "react-icons/vsc";
import { MdArrowBackIos, MdArrowForwardIos } from "react-icons/md";

export default function Home() {
  return (
    <>
      <Head>
        <title>North Advantures</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" max-w-screen-2xl m-auto">
        <section className=" bg-[url('../public/bg4.jpg')] bg-no-repeat bg-cover bg-center pb-20">

          <div className=" flex justify-between mx-3 pt-5 text-white lg:flex lg:mx-32 lg:pt-5">
            <div>
              <h3 className=" font-semibold text-xl lg:text-2xl">Web design</h3>
            </div>

            <div className="flex-col text-center mx-auto lg:flex lg:flex-row lg:mt-10">
              <GiMountains className="text-2xl mx-auto lg:text-5xl" />
              <h1 className=" uppercase font-bold text-xl flex-wrap lg:text-5xl lg:pl-5 lg: max-w-sm">
                North Advantures
              </h1>
            </div>
            <div>
              <h3 className=" font-semibold text-xl lg:text-2xl">
                Concept 2022
              </h3>
            </div>
          </div>

          <div className="bg-[url('../public/bg4.jpg')] bg-no-repeat bg-cover bg-center mx-3 lg:mx-32 rounded-3xl ring-4 lg:ring-8 ring-black mt-20 pb-20">
            <nav className="pt-10 lg:flex lg:flex-row lg:justify-between">
              <div className="flex-col text-center mx-auto text-white lg:flex lg:flex-row">
                <GiMountains className="text-xl mx-auto lg:text-4xl" />
                <h3 className=" uppercase font-bold text-xl flex-wrap pl-3 lg:text-3xl lg: max-w-sm">
                  North Advantures
                </h3>
              </div>

              <div className="mx-auto">
                <ul className=" hidden lg:flex lg:flex-row">
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    About Us
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Tour
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Location
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Contac Us
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Blog
                  </li>
                </ul>
              </div>

              <div className="flex justify-center pt-5 gap-3 text-white lg:flex lg:text-xl lg:mx-auto lg:pt-0">
                <HiMagnifyingGlass className=" cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
                <IoIosMan className=" cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
                <BiWorld className=" cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
              </div>
            </nav>

            <div className="mx-auto text-center py-10">
              <h1 className=" uppercase italic font-bold text-white text-4xl lg:text-9xl">
                Alaska
              </h1>
            </div>

            <div className=" px-3 lg:flex lg:flex-row lg:justify-between lg:mx-40 lg:px-0">
              <p className=" font-medium text-white text-xl lg:leading-8 lg:max-w-xl">
                Alaska is the most extensive state of the United States, famouse
                for its naturalresorurces.On the teritory of Alaska, there are
                more then 3 milion lakes and 3 thousend rivers.
              </p>

              <div className="flex flex-row pt-5 pl-3 lg:pt-0 lg:pl-0">
                <VscPlayCircle className="text-white cursor-pointer hover:scale-125 transition duration-300 ease-in-out text-3xl lg:text-5xl" />

                <div className="flex-col pl-5">
                  <h3 className=" uppercase font-semibold text-white text-xl lg:w-20">
                    Watching Video
                  </h3>
                  <p className="font-semibold text-white">2:14</p>
                </div>
              </div>
            </div>

            <button className=" uppercase font-semibold text-white bg-red-700 mt-5 ml-5 lg:mt-5 lg:ml-40 py-5 px-12 rounded-xl cursor-pointer hover:scale-110 transition duration-300 ease-in-out">
              Discover
            </button>

            <div className="flex items-center pt-5 pl-5 lg:pl-0 lg:pt-5 lg:mx-40">
              <MdArrowBackIos className="text-white text-3xl cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
              <div className="flex">
                <h3 className="text-white font-bold text-5xl">02</h3>
                <h3 className="pl-1 text-gray-400 font-bold text-xl">/03</h3>
              </div>
              <MdArrowForwardIos className="text-white text-3xl cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
            </div>

            <div className="flex flex-col pt-5 lg:flex lg:flex-row lg:justify-between lg:mx-32 lg:pt-10">
              <ul className="flex flex-col items-center lg:flex lg:flex-row">
                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-blue-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">Facebook</a>
                </li>
                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-orange-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">Instagram</a>
                </li>

                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-red-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">YouTube</a>
                </li>

                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-blue-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">Linkedin</a>
                </li>
              </ul>
              <h3 className="text-xl text-white text-center pt-5 lg:pt-0">
                Copyright 2022
              </h3>
            </div>
          </div>
        </section>

        <section className=" bg-gradient-to-b from-gray-900 to-gray-700 pt-20">
          <div className="text-center mx-10 py-20 lg:mx-32 lg:text-left">
            <p className="text-gray-100 font-semibold text-base lg:text-xl">
              About
            </p>
            <h3 className="text-gray-100 font-semibold leading-8 text-xl lg:text-2xl pt-3">
              Concept and design of website for agency that organizex tours to
              North countrys.
            </h3>
          </div>

          <div className="text-center lg:mx-32 lg:text-left">
            <p className="text-gray-100 font-semibold text-base lg:text-xl">
              Typo
            </p>
          </div>

          <div className="flex flex-col text-center pt-3 pb-20 py-20 lg:flex lg:flex-row lg:justify-between lg:mx-32 lg:text-left">
            <div>
              <h2 className=" uppercase text-gray-100 font-bold text-2xl lg:text-5xl">
                My Raid Pro
              </h2>
              <p className="font-semibold text-gray-500">Title</p>
            </div>

            <div className="pt-5 lg:pt-0">
              <h3 className=" uppercase text-gray-100 font-bold text-xl lg:text-3xl">
                Oswald
              </h3>
              <p className="font-semibold text-gray-500">Title</p>
            </div>
            <div className="pt-5 lg:pt-0">
              <h3 className="text-gray-100 text-xl lg:text-3xl">Roboto</h3>
              <p className="font-semibold text-gray-500">Content</p>
            </div>
          </div>

          <div className="text-center mx-auto pb-20 lg:mx-32">
            <p className="text-gray-100 pb-5 font-semibold text-base lg:text-xl">
              Color
            </p>

            <div className="flex flex-col lg:flex lg:flex-row lg:justify-between items-center">
              <div className="w-32 py-10">
                <div className="w-32 h-32 lg:w-44 lg:h-44 rounded-lg bg-white"></div>
                <p className=" float-right text-gray-100 pt-3">#fffff</p>
              </div>

              <div className="w-32 py-10">
                <div className="w-32 h-32 lg:w-44 lg:h-44 rounded-lg bg-gray-400"></div>
                <p className=" float-right text-gray-100 pt-3">#95959</p>
              </div>

              <div className="w-32 py-10">
                <div className="w-32 h-32 lg:w-44 lg:h-44 rounded-lg bg-gray-900"></div>
                <p className=" float-right text-gray-100 pt-3">#16141f</p>
              </div>

              <div className="w-32 py-10">
                <div className="w-32 h-32 lg:w-44 lg:h-44 rounded-lg bg-black"></div>
                <p className=" float-right text-gray-100 pt-3">#00000</p>
              </div>

              <div className="w-32 py-10">
                <div className="w-32 h-32 lg:w-44 lg:h-44 rounded-lg bg-red-600"></div>
                <p className=" float-right text-gray-100 pt-3">#eb2632</p>
              </div>
            </div>
          </div>
        </section>

        <section className="py-20 bg-gradient-to-b from-gray-700 to-gray-500">
          <div className="text-center lg:mx-32 lg:text-left">
            <p className=" font-semibold text-gray-500">Design first screen</p>
          </div>

          <div className="bg-[url('../public/bg6.jpg')] bg-no-repeat bg-cover bg-center mx-3 lg:mx-32 rounded-3xl  ring-4 lg:ring-8 ring-black mt-20 pb-10">
            <nav className="pt-20 lg:flex lg:flex-row lg:justify-between">
              <div className="flex-col text-center mx-auto text-white lg:flex lg:flex-row">
                <GiMountains className="text-xl mx-auto lg:text-4xl" />
                <h3 className=" uppercase font-bold text-xl flex-wrap pl-3 lg:text-3xl lg: max-w-sm">
                  North Advantures
                </h3>
              </div>

              <div className="mx-auto">
                <ul className=" hidden lg:flex lg:flex-row">
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    About Us
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Tour
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Location
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Contac Us
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Blog
                  </li>
                </ul>
              </div>

              <div className="flex justify-center pt-5 gap-3 text-white lg:flex lg:text-xl lg:mx-auto lg:pt-0">
                <HiMagnifyingGlass className=" cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
                <IoIosMan className=" cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
                <BiWorld className=" cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
              </div>
            </nav>

            <div className="mx-auto text-center py-10">
              <h1 className=" uppercase italic font-bold text-white text-4xl lg:text-9xl">
                Iceland
              </h1>
            </div>

            <div className=" px-3 lg:flex lg:flex-row lg:justify-between lg:mx-40 lg:px-0">
              <p className=" font-medium text-white text-xl lg:leading-8 lg:max-w-xl">
                The northern country of Iclands has incruedible beaty and charm.
                In winter here you will find expansefor skiers,snowcovered firs
                and cozy warm houses with live fire and hot drinks.
              </p>

              <div className="flex flex-row pt-5 pl-3 lg:pt-0 lg:pl-0">
                <VscPlayCircle className="text-white cursor-pointer hover:scale-125 transition duration-300 ease-in-out text-3xl lg:text-5xl" />

                <div className="flex-col pl-5">
                  <h3 className=" uppercase font-semibold text-white text-xl lg:w-20">
                    Watching Video
                  </h3>
                  <p className="font-semibold text-white">2:14</p>
                </div>
              </div>
            </div>

            <button className=" uppercase font-semibold text-white bg-red-700 mt-5 ml-5 lg:mt-5 lg:ml-40 py-5 px-12 rounded-xl cursor-pointer hover:scale-110 transition duration-300 ease-in-out">
              Discover
            </button>

            <div className="flex items-center pt-5 pl-5 lg:pl-0 lg:pt-5 lg:mx-40">
              <MdArrowBackIos className="text-white text-3xl cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
              <div className="flex">
                <h3 className="text-white font-bold text-5xl">02</h3>
                <h3 className="pl-1 text-gray-400 font-bold text-xl">/03</h3>
              </div>
              <MdArrowForwardIos className="text-white text-3xl cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
            </div>

            <div className="flex flex-col pt-5 lg:flex lg:flex-row lg:justify-between lg:mx-32 lg:pt-10">
              <ul className="flex flex-col items-center lg:flex lg:flex-row">
                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-blue-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">Facebook</a>
                </li>
                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-orange-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">Instagram</a>
                </li>

                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-red-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">YouTube</a>
                </li>

                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-blue-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">Linkedin</a>
                </li>
              </ul>
              <h3 className="text-xl text-white text-center pt-5 lg:pt-0">
                Copyright 2022
              </h3>
            </div>
          </div>

          <div className="bg-[url('../public/bg4.jpg')] bg-no-repeat bg-cover bg-center mx-3 lg:mx-32 rounded-3xl  ring-4 lg:ring-8 ring-black mt-20 pb-10">
            <nav className="pt-20 lg:flex lg:flex-row lg:justify-between">
              <div className="flex-col text-center mx-auto text-white lg:flex lg:flex-row">
                <GiMountains className="text-xl mx-auto lg:text-4xl" />
                <h3 className=" uppercase font-bold text-xl flex-wrap pl-3 lg:text-3xl lg: max-w-sm">
                  North Advantures
                </h3>
              </div>

              <div className="mx-auto">
                <ul className=" hidden lg:flex lg:flex-row">
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    About Us
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Tour
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Location
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Contac Us
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Blog
                  </li>
                </ul>
              </div>

              <div className="flex justify-center pt-5 gap-3 text-white lg:flex lg:text-xl lg:mx-auto lg:pt-0">
                <HiMagnifyingGlass className=" cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
                <IoIosMan className=" cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
                <BiWorld className=" cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
              </div>
            </nav>

            <div className="mx-auto text-center py-10">
              <h1 className=" uppercase italic font-bold text-white text-4xl lg:text-9xl">
                Alaska
              </h1>
            </div>

            <div className=" px-3 lg:flex lg:flex-row lg:justify-between lg:mx-40 lg:px-0">
              <p className=" font-medium text-white text-xl lg:leading-8 lg:max-w-xl">
                Alaska is the most extensive state of the United States, famouse
                for its naturalresorurces.On the teritory of Alaska, there are
                more then 3 milion lakes and 3 thousend rivers.
              </p>

              <div className="flex flex-row pt-5 pl-3 lg:pt-0 lg:pl-0">
                <VscPlayCircle className="text-white cursor-pointer hover:scale-125 transition duration-300 ease-in-out text-3xl lg:text-5xl" />

                <div className="flex-col pl-5">
                  <h3 className=" uppercase font-semibold text-white text-xl lg:w-20">
                    Watching Video
                  </h3>
                  <p className="font-semibold text-white">2:14</p>
                </div>
              </div>
            </div>

            <button className=" uppercase font-semibold text-white bg-red-700 mt-5 ml-5 lg:mt-5 lg:ml-40 py-5 px-12 rounded-xl cursor-pointer hover:scale-110 transition duration-300 ease-in-out">
              Discover
            </button>

            <div className="flex items-center pt-5 pl-5 lg:pl-0 lg:pt-5 lg:mx-40">
              <MdArrowBackIos className="text-white text-3xl cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
              <div className="flex">
                <h3 className="text-white font-bold text-5xl">02</h3>
                <h3 className="pl-1 text-gray-400 font-bold text-xl">/03</h3>
              </div>
              <MdArrowForwardIos className="text-white text-3xl cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
            </div>

            <div className="flex flex-col pt-5 lg:flex lg:flex-row lg:justify-between lg:mx-32 lg:pt-10">
              <ul className="flex flex-col items-center lg:flex lg:flex-row">
                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-blue-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">Facebook</a>
                </li>
                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-orange-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">Instagram</a>
                </li>

                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-red-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">YouTube</a>
                </li>

                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-blue-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">Linkedin</a>
                </li>
              </ul>
              <h3 className="text-xl text-white text-center pt-5 lg:pt-0">
                Copyright 2022
              </h3>
            </div>
          </div>

          <div className="bg-[url('../public/bg3.jpg')] bg-no-repeat bg-cover bg-center mx-3 lg:mx-32 rounded-3xl  ring-4 lg:ring-8 ring-black mt-20 pb-10">
            <nav className="pt-20 lg:flex lg:flex-row lg:justify-between">
              <div className="flex-col text-center mx-auto text-white lg:flex lg:flex-row">
                <GiMountains className="text-xl mx-auto lg:text-4xl" />
                <h3 className=" uppercase font-bold text-xl flex-wrap pl-3 lg:text-3xl lg: max-w-sm">
                  North Advantures
                </h3>
              </div>

              <div className="mx-auto">
                <ul className=" hidden lg:flex lg:flex-row">
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    About Us
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Tour
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Location
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Contac Us
                  </li>
                  <li className="font-bold text-white uppercase text-xl cursor-pointer pl-5  hover:scale-110 transition duration-300 ease-in-out ">
                    Blog
                  </li>
                </ul>
              </div>

              <div className="flex justify-center pt-5 gap-3 text-white lg:flex lg:text-xl lg:mx-auto lg:pt-0">
                <HiMagnifyingGlass className=" cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
                <IoIosMan className=" cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
                <BiWorld className=" cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
              </div>
            </nav>

            <div className="mx-auto text-center py-10">
              <h1 className=" uppercase italic font-bold text-white text-4xl lg:text-9xl">
                Norway
              </h1>
            </div>

            <div className=" px-3 lg:flex lg:flex-row lg:justify-between lg:mx-40 lg:px-0">
              <p className=" font-medium text-white text-xl lg:leading-8 lg:max-w-xl">
                This country the beauty of its harsh nature can eclipse many
                tropical countries and popular resorts. No guest of this
                Scandinavian country will be left indifferent by the stunning
                fjords,the glaciers glittering in the sun,the endless forests
                and stormy waterfalls.
              </p>

              <div className="flex flex-row pt-5 pl-3 lg:pt-0 lg:pl-0">
                <VscPlayCircle className="text-white cursor-pointer hover:scale-125 transition duration-300 ease-in-out text-3xl lg:text-5xl" />

                <div className="flex-col pl-5">
                  <h3 className=" uppercase font-semibold text-white text-xl lg:w-20">
                    Watching Video
                  </h3>
                  <p className="font-semibold text-white">2:14</p>
                </div>
              </div>
            </div>

            <button className=" uppercase font-semibold text-white bg-red-700 mt-5 ml-5 lg:mt-5 lg:ml-40 py-5 px-12 rounded-xl cursor-pointer hover:scale-110 transition duration-300 ease-in-out">
              Discover
            </button>

            <div className="flex items-center pt-5 pl-5 lg:pl-0 lg:pt-5 lg:mx-40">
              <MdArrowBackIos className="text-white text-3xl cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
              <div className="flex">
                <h3 className="text-white font-bold text-5xl">02</h3>
                <h3 className="pl-1 text-gray-400 font-bold text-xl">/03</h3>
              </div>
              <MdArrowForwardIos className="text-white text-3xl cursor-pointer hover:scale-125 transition duration-300 ease-in-out" />
            </div>

            <div className="flex flex-col pt-5 lg:flex lg:flex-row lg:justify-between lg:mx-32 lg:pt-10">
              <ul className="flex flex-col items-center lg:flex lg:flex-row">
                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-blue-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">Facebook</a>
                </li>
                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-orange-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">Instagram</a>
                </li>

                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-red-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">YouTube</a>
                </li>

                <li className="text-gray-200 pl-5 pt-5 lg:pt-0 text-xl cursor-pointer hover:text-blue-500 hover:scale-110 transition duration-300 ease-in-out">
                  <a href="#">Linkedin</a>
                </li>
              </ul>
              <h3 className="text-xl text-white text-center pt-5 lg:pt-0">
                Copyright 2022
              </h3>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
